const strings = {
  emailPlaceholderText: 'johndoe@gmail.com',
  namePlaceholderText: 'John Doe',
  passwordPlaceholderText: 'Enter your password',
  confirmPasswordPlaceholderText: 'Confirm your password',
  registerWithKojo: 'Register With Kojo',
  fullNameSubHeading: 'Full Name',
  emailSubHeading: 'Email',
  passwordSubHeading: 'Password',
  confirmPasswordSubHeading: 'Confirm Password',
  register: 'Register',
  termsAndConditions: 'Terms & Conditions',
  and: 'and',
  privacyPolicy: 'Privacy Policy',
  registeringWithKojoHeadline: 'By registering you agree to Kojo\'s ',
  facebook: 'Facebook',
  google: 'Google',
  forgotPassword: 'Forgot Password?',
  login: 'Login',
  dontHaveAnAccount: 'Don\'t have an account?',
  registerNow: 'Register Now.',
  welcomeLogin: 'LOGIN',
  welcomeSignUp: 'SIGN UP',
  checkYourEmail: 'Check your Email',
  resetLinkSent: 'We have sent you a reset password link on your registered email address.',
  goToEmail: 'Go To Email',
  viewInventory: 'View Inventory',
  editItems: 'Edit Items',
  addItems: 'Add Items',
  viewClients: 'View Clients',
  iAmA: 'I am a',
  iOwnA:'I own a',
  supplier: 'Supplier',
  restaurant: 'Restaurant',
  loading: 'Loading, please wait...',
}

export default strings
