const strings = {
  emailPlaceholderText: 'johndoe@gmail.com',
  namePlaceholderText: 'John Doe',
  passwordPlaceholderText: 'Enter your password',
  confirmPasswordPlaceholderText: 'Confirm your password',
  registerWithKojo: 'Register With Kojo',
  fullNameSubHeading: 'Full Name',
  emailSubHeading: 'Email',
  passwordSubHeading: 'Password',
  confirmPasswordSubHeading: 'Confirm Password',
  register: 'Register',
  termsAndConditions: 'Terms & Conditions',
  and: 'and',
  privacyPolicy: 'Privacy Policy',
  registeringWithKojoHeadline: 'By registering you agree to Kojo\'s ',
  facebook: 'Facebook',
  google: 'Google',
  forgotPassword: 'Forgot Password?',
  login: 'Login',
  dontHaveAnAccount: 'Don\'t have an account?',
  registerNow: 'Register Now.',
  welcomeLogin: 'LOGIN',
  welcomeSignUp: 'SIGN UP',
  checkYourEmail: 'Check your Email',
  resetLinkSent: 'We have sent you a reset password link on your registered email address.',
  goToEmail: 'Go To Email',
  viewInventory: 'View Inventory',
  editItems: 'Edit Items',
  addItems: 'Add Items',
  viewClients: 'View Clients',
  iAmA: 'I am a',
  iOwnA:'I own a',
  supplier: 'Supplier',
  restaurant: 'Restaurant',
  loading: 'Loading, please wait...',
  edit: 'Edit',
  inventoryTypeText: 'Inventory type ',
  inventoryTypeSubheading: 'Inventory Type',
  inventoryName: 'Inventory Name',
  inventoryNamePlaceholderText: 'Add inventory name',
  inventoryQuantityAvailable: 'Quantity Available',
  inventoryQuantityAvailablePlaceholderText: 'Enter the quantity',
  inventoryPricePerUnit: 'Price per Unit',
  inventoryPricePerUnitPlaceholderText: 'Enter price per unit',
  addInventoryText: 'Add Inventory',
  inventoryDocumentName: 'Inventory Title',
  inventoryDocumentCategory: 'Item Category',
  inventoryDocumentNamePlaceholderText: 'Add an Item Title',
  inventoryUploadImage: 'Upload Image',
  nameCannotBeEmpty: 'Name cannot be empty',
  emailCannotBeEmpty: 'Email cannot be empty',
  passwordCannotBeEmpty: 'Password cannot be empty',
  confirmPasswordCannotBeEmpty: 'Either passwords cannot be empty',
  passwordsDoNotMatch: 'Passwords do not match',
  nameErrorMessage: 'Please enter your full name with no special characters.',
  emailErrorMessage: 'Please enter a properly formatted email address.',
  passwordErrorMessage: 'Password must have at least 6 characters',
  add: 'Add'
}

export default strings
